name: Build DAZ Studio Plugin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Create Plugin Files
      shell: cmd
      run: |
        echo Building Plugin DLL...

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CustomShelfPlugin-DLL
        path: |
          *.dll
